"""Run every resilience scenario back to back and emit a markdown report.

    python scripts/drills.py --rps 25 --duration 24

Writes docs/benchmarks.md so the numbers in the README are reproducible rather
than aspirational.
"""

from __future__ import annotations

import argparse
import contextlib
import json
import sys
import time
from pathlib import Path

import httpx

with contextlib.suppress(AttributeError, OSError):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

SCENARIOS = ["baseline", "worker-loss", "broker-outage", "db-slowdown", "poison-payloads", "burst"]
REPORT = Path(__file__).resolve().parents[1] / "docs" / "benchmarks.md"


def run_one(client: httpx.Client, scenario: str, rps: int, duration: int) -> dict:
    body = {
        "scenario": scenario,
        "rps": rps,
        "duration_s": duration,
        "fault_at_s": max(4, duration // 3),
        "fault_duration_s": max(6, duration // 3),
        "concurrency": min(128, rps * 2),
        "model": "sentiment-v1",
    }
    started = client.post("/v1/loadtest", json=body).json()
    run_id = started["id"]
    print(f"\n{scenario}: run {run_id}", flush=True)
    while True:
        time.sleep(4)
        detail = client.get(f"/v1/loadtest/{run_id}").json()
        if detail["status"] != "running":
            break
        print("  ...", flush=True)
    metrics = detail.get("metrics") or {}
    verdict = detail.get("verdict") or {}
    print(
        f"  rps={metrics.get('achieved_rps')} "
        f"p95_submit={(metrics.get('submit_latency_ms') or {}).get('p95')}ms "
        f"p95_e2e={(metrics.get('end_to_end_ms') or {}).get('p95')}ms "
        f"lost={verdict.get('lost_jobs')} recovery={verdict.get('recovery_seconds')}s",
        flush=True,
    )
    return detail


def markdown(rows: list[dict], rps: int, duration: int, platform: dict) -> str:
    header = [
        "# Benchmarks",
        "",
        "Generated by `python scripts/drills.py` against a live stack. Every row is one",
        "drill: paced load, one injected fault, then full reconciliation of accepted jobs",
        "against terminal states.",
        "",
        f"- target rate: **{rps} rps** for **{duration}s** per scenario",
        f"- broker: **{platform.get('broker')}** · store: **{platform.get('database')}** · "
        f"cache: **{platform.get('cache', {}).get('backend')}**",
        f"- generated: {time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())}",
        "",
        "| scenario | achieved rps | submit p50 / p95 / p99 | end-to-end p95 | completed | retries | DLQ | drain | recovery | lost |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        metrics = row.get("metrics") or {}
        verdict = row.get("verdict") or {}
        submit = metrics.get("submit_latency_ms") or {}
        e2e = metrics.get("end_to_end_ms") or {}
        recovery = verdict.get("recovery_seconds")
        drain = metrics.get("queue_drain_s")
        header.append(
            "| `{scenario}` | {rps} | {p50} / {p95} / {p99} ms | {e2e} ms | {done} | {retries} | {dlq} | {drain} | {recovery} | **{lost}** |".format(
                scenario=row["scenario"],
                rps=metrics.get("achieved_rps", "—"),
                p50=submit.get("p50", "—"),
                p95=submit.get("p95", "—"),
                p99=submit.get("p99", "—"),
                e2e=e2e.get("p95", "—"),
                done=metrics.get("completed_jobs", "—"),
                retries=metrics.get("retries", "—"),
                dlq=metrics.get("dlq", "—"),
                drain=f"{drain}s" if drain is not None else "not drained in 90s",
                recovery=f"{recovery}s" if recovery is not None else "n/a",
                lost=verdict.get("lost_jobs", "—"),
            )
        )

    header += [
        "",
        "## Reading the table",
        "",
        "- **lost** is the number of jobs the gateway accepted that never reached a terminal",
        "  state. It is the headline correctness result and must be zero in every row.",
        "- **recovery** is the time from the fault clearing to completion throughput returning",
        "  above half the pre-fault median. `n/a` means no fault was injected.",
        "- **drain** is how long the backlog took to clear after the load stopped.",
        "- `poison-payloads` intentionally produces failures and dead letters; the point is that",
        "  the queue keeps moving and every job is still accounted for.",
        "",
        "## Notes on the environment",
        "",
        "These numbers come from whatever stack the script was pointed at. The database-backed",
        "queue on SQLite is convenient but serialises writes, which caps throughput on a laptop.",
        "Run `docker compose up -d` (Postgres + Redpanda + Redis) and re-run the script for",
        "numbers that reflect the production path.",
        "",
    ]
    return "\n".join(header)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--lab", default="http://127.0.0.1:8100")
    parser.add_argument("--gateway", default="http://127.0.0.1:8000")
    parser.add_argument("--rps", type=int, default=25)
    parser.add_argument("--duration", type=int, default=24)
    parser.add_argument("--scenarios", nargs="*", default=SCENARIOS)
    args = parser.parse_args()

    lab = httpx.Client(base_url=args.lab, timeout=60.0)
    gateway = httpx.Client(base_url=args.gateway, timeout=30.0, headers={"X-API-Key": "demo-key-aegisflow"})
    platform = gateway.get("/v1/stats").json()["platform"]

    rows = [run_one(lab, scenario, args.rps, args.duration) for scenario in args.scenarios]

    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(markdown(rows, args.rps, args.duration, platform), encoding="utf-8")
    (REPORT.parent / "benchmarks.json").write_text(
        json.dumps([{k: r[k] for k in ("id", "scenario", "metrics", "verdict")} for r in rows], indent=2),
        encoding="utf-8",
    )
    print(f"\nwrote {REPORT}")
    losses = sum((r.get("verdict") or {}).get("lost_jobs") or 0 for r in rows)
    print(f"total lost jobs across {len(rows)} drills: {losses}")
    return 0 if losses == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
